services:
  - type: web
    name: social-echo
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: NEXTAUTH_SECRET
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: STRIPE_STARTER_PRICE_ID
        sync: false
      - key: STRIPE_PRO_PRICE_ID
        sync: false
      - key: STRIPE_AGENCY_PRICE_ID
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_REPLY_TO
        sync: false
      - key: OPENAI_API_KEY
        sync: false

